# Generated by Django 6.0.6 on 2026-06-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkin_time', models.TimeField()),
                ('base_daily_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking')], max_length=20)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='CHECKED_IN', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='master.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='master.room')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField()),
                ('checkout_time', models.TimeField()),
                ('total_days', models.PositiveIntegerField()),
                ('balance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='reservations.checkin')),
            ],
        ),
    ]
