# Generated by Django 6.0.6 on 2026-06-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_customer_id_proof'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='master.customer'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='reservations.checkin'),
        ),
    ]
