# Generated by Django 6.0.6 on 2026-06-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_checkin_customer_alter_checkout_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkout',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
