# Generated by Django 6.0.6 on 2026-06-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_checkin_remarks_checkin_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guest Checkout', 'verbose_name_plural': 'Guest Checkouts'},
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pay_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking')], default='UPI', max_length=20),
        ),
    ]
