# Generated by Django 6.0.6 on 2026-06-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_checkout_options_alter_checkout_pay_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={},
        ),
        migrations.AddField(
            model_name='checkin',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkin',
            name='base_daily_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pay_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking')], max_length=20),
        ),
    ]
