# Generated by Django 6.0.6 on 2026-06-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_checkout_options_checkin_advance_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='pay_type',
            new_name='pay_mode',
        ),
    ]
