# Generated by Django 6.0.6 on 2026-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_proof',
            field=models.FileField(upload_to='customer_id_proofs/'),
        ),
    ]
