# Generated by Django 6.0.6 on 2026-06-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_customer_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='customer_id_proofs/'),
        ),
    ]
